### ISSUE TITLE
Code for the video?

### ISSUE THREAD

**Issue by vvolhejn** [WampyCakes/manim-rubikscube#7]
Would you mind sharing the code you used to produce the cube's look from [the video](https://www.youtube.com/watch?v=xMY0mPPY25k)? They're really nice!

**Comment by WampyCakes** [comment]
I would like to keep that to myself. :)

**Comment by vvolhejn** [comment]
Hi, sorry, I should've been more specific. I'm only looking for the look of the cube which is different from what's in this repo. So not the animations and the rest. The README currently says "Wonder how Manim RubiksCube looks so much better in this video than my docs and examples show? I have made a lot of technical upgrades and aesthetic updates to the plugin locally that are not yet ready for GitHub or a new release. Stay patient for the update! Until then, you can locally edit manim-rubikscube yourself to replicate the aesthetics I have in this video, if you so desire."

Could you share a [Gist](https://gist.github.com/) or something that it would be possible to infer this from, even if the code is not runnable? It's great that you shared this library to help other creators; and this would be a nice step in the same open-source spirit.
